name = "UniGo"
grammar = "unigo"
path_suffixes = ["ug"]
line_comments = ["// "]
tab_size = 4
hard_tabs = true
autoclose_before = ";:.,=}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["string", "comment"] },
]
word_characters = ["_"]
