package gogen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/printer"
	gotok "go/token"
	"go/types"
	"strconv"
	"strings"

	gast "unigo/compiler/ast"
	"unigo/compiler/check"
	"unigo/compiler/names"
	"unigo/compiler/token"
)

type gen struct {
	info *check.Info
	fset *gotok.FileSet
	tf   *gotok.File
	at   int
	errN int
}

func Generate(file *gast.File, info *check.Info) ([]byte, error) {
	if info == nil {
		info = &check.Info{}
	}
	g := &gen{info: info, fset: gotok.NewFileSet()}
	g.tf = g.fset.AddFile("generated.go", 1, 1<<20)
	gf := &ast.File{Name: ast.NewIdent(file.Package.Name)}
	gf.Package = g.pos()
	if imps := g.imports(file); imps != nil {
		gf.Decls = append(gf.Decls, imps...)
	}
	for _, d := range file.Decls {
		gf.Decls = append(gf.Decls, g.decl(d)...)
	}
	var buf bytes.Buffer
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 4}
	if err := cfg.Fprint(&buf, g.fset, gf); err != nil {
		return nil, err
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by unigo; DO NOT EDIT.\n\n")
	out.Write(buf.Bytes())
	if !bytes.HasSuffix(out.Bytes(), []byte("\n")) {
		out.WriteByte('\n')
	}
	return out.Bytes(), nil
}

func (g *gen) pos() gotok.Pos {
	p := g.tf.Pos(g.at)
	g.at++
	return p
}

func (g *gen) imports(file *gast.File) []ast.Decl {
	if len(file.Imports) == 0 && len(g.info.Imports) == 0 {
		return nil
	}
	var specs []ast.Spec
	byLocal := map[string]*check.ImportInfo{}
	for _, im := range g.info.Imports {
		byLocal[im.Local] = im
	}
	for _, im := range file.Imports {
		if im.Path == "" || im.Name == "" || im.Name == "_bad" {
			continue
		}
		spec := &ast.ImportSpec{
			Path: &ast.BasicLit{Kind: gotok.STRING, Value: strconv.Quote(im.Path)},
		}
		info := byLocal[im.Name]
		if info == nil || info.Name != im.Name {
			spec.Name = ast.NewIdent(im.Name)
		}
		specs = append(specs, spec)
	}
	var decls []ast.Decl
	if len(specs) > 0 {
		decls = append(decls, &ast.GenDecl{
			Tok:    gotok.IMPORT,
			Lparen: g.pos(),
			Specs:  specs,
			Rparen: g.pos(),
		})
	}
	for _, im := range g.info.Imports {
		if im.Used || im.Pkg == nil {
			continue
		}
		if d := g.useImport(im); d != nil {
			decls = append(decls, d)
		}
	}
	return decls
}

func (g *gen) useImport(im *check.ImportInfo) ast.Decl {
	if name, ok := exportedValue(im.Pkg); ok {
		return &ast.GenDecl{
			Tok: gotok.VAR,
			Specs: []ast.Spec{
				&ast.ValueSpec{
					Names:  []*ast.Ident{ast.NewIdent("_")},
					Values: []ast.Expr{&ast.SelectorExpr{X: ast.NewIdent(im.Local), Sel: ast.NewIdent(name)}},
				},
			},
		}
	}
	if name, ok := exportedType(im.Pkg); ok {
		return &ast.GenDecl{
			Tok: gotok.TYPE,
			Specs: []ast.Spec{
				&ast.TypeSpec{
					Name:   ast.NewIdent("unigoBindUse" + im.Local),
					Assign: g.pos(),
					Type:   &ast.SelectorExpr{X: ast.NewIdent(im.Local), Sel: ast.NewIdent(name)},
				},
			},
		}
	}
	return nil
}

func exportedValue(pkg *types.Package) (string, bool) {
	for _, name := range pkg.Scope().Names() {
		if !gotok.IsExported(name) {
			continue
		}
		switch pkg.Scope().Lookup(name).(type) {
		case *types.Func, *types.Var, *types.Const:
			return name, true
		}
	}
	return "", false
}

func exportedType(pkg *types.Package) (string, bool) {
	for _, name := range pkg.Scope().Names() {
		if !gotok.IsExported(name) {
			continue
		}
		if _, ok := pkg.Scope().Lookup(name).(*types.TypeName); ok {
			return name, true
		}
	}
	return "", false
}

func (g *gen) decl(d gast.Decl) []ast.Decl {
	switch d := d.(type) {
	case *gast.ConstDecl:
		return []ast.Decl{g.constGen(d)}
	case *gast.VarDecl:
		return g.fileVar(d)
	case *gast.FuncDecl:
		return []ast.Decl{g.funcDecl(d)}
	case *gast.EnumDecl:
		return g.enumDecl(d)
	case *gast.StructDecl:
		return []ast.Decl{g.structDecl(d)}
	case *gast.InterfaceDecl:
		return g.interfaceDecl(d)
	case *gast.NewtypeDecl:
		return []ast.Decl{&ast.GenDecl{Tok: gotok.TYPE, Specs: []ast.Spec{&ast.TypeSpec{
			Name: ast.NewIdent(d.Name),
			Type: g.typeExpr(d.Type),
		}}}}
	case *gast.AliasDecl:
		return []ast.Decl{&ast.GenDecl{Tok: gotok.TYPE, Specs: []ast.Spec{&ast.TypeSpec{
			Name:   ast.NewIdent(d.Name),
			Assign: g.pos(),
			Type:   g.typeExpr(d.Type),
		}}}}
	default:
		return nil
	}
}

func (g *gen) constGen(d *gast.ConstDecl) ast.Decl {
	spec := &ast.ValueSpec{
		Names:  []*ast.Ident{ast.NewIdent(d.Name)},
		Type:   g.typeExpr(d.Type),
		Values: []ast.Expr{g.expr(d.Value)},
	}
	return &ast.GenDecl{Tok: gotok.CONST, Specs: []ast.Spec{spec}}
}

func (g *gen) fileVar(d *gast.VarDecl) []ast.Decl {
	if len(d.Specs) == 1 && (g.info.Inits[d] == nil || !g.info.Inits[d].Omitted) {
		sp := d.Specs[0]
		spec := &ast.ValueSpec{
			Names:  []*ast.Ident{ast.NewIdent(sp.Name)},
			Type:   g.typeExpr(sp.Type),
			Values: []ast.Expr{g.exprAs(d.Value, sp.Type)},
		}
		return []ast.Decl{&ast.GenDecl{Tok: gotok.VAR, Specs: []ast.Spec{spec}}}
	}
	return nil
}

func (g *gen) enumDecl(d *gast.EnumDecl) []ast.Decl {
	typeDecl := &ast.GenDecl{Tok: gotok.TYPE, Specs: []ast.Spec{&ast.TypeSpec{
		Name: ast.NewIdent(d.Name),
		Type: ast.NewIdent("int"),
	}}}
	specs := make([]ast.Spec, len(d.Members))
	for i, m := range d.Members {
		vs := &ast.ValueSpec{Names: []*ast.Ident{ast.NewIdent(d.Name + "_" + m.Name)}}
		if i == 0 {
			vs.Type = ast.NewIdent(d.Name)
			vs.Values = []ast.Expr{&ast.BinaryExpr{
				X:  ast.NewIdent("iota"),
				Op: gotok.ADD,
				Y:  &ast.BasicLit{Kind: gotok.INT, Value: "1"},
			}}
		}
		specs[i] = vs
	}
	constDecl := &ast.GenDecl{Tok: gotok.CONST, Lparen: g.pos(), Specs: specs, Rparen: g.pos()}
	return []ast.Decl{typeDecl, constDecl}
}

func (g *gen) structDecl(d *gast.StructDecl) ast.Decl {
	fields := make([]*ast.Field, len(d.Fields))
	for i, f := range d.Fields {
		fields[i] = &ast.Field{
			Names: []*ast.Ident{ast.NewIdent(names.Export(f.Name))},
			Type:  g.typeExpr(f.Type),
			Tag:   &ast.BasicLit{Kind: gotok.STRING, Value: fmt.Sprintf("`json:%q`", f.Name)},
		}
	}
	return &ast.GenDecl{Tok: gotok.TYPE, Specs: []ast.Spec{&ast.TypeSpec{
		Name: ast.NewIdent(d.Name),
		Type: &ast.StructType{Fields: &ast.FieldList{List: fields}},
	}}}
}

func (g *gen) interfaceDecl(d *gast.InterfaceDecl) []ast.Decl {
	methods := make([]*ast.Field, len(d.Methods))
	for i, m := range d.Methods {
		methods[i] = &ast.Field{
			Names: []*ast.Ident{ast.NewIdent(m.Name)},
			Type:  g.funcType(m.Params, m.Result),
		}
	}
	iface := &ast.GenDecl{Tok: gotok.TYPE, Specs: []ast.Spec{&ast.TypeSpec{
		Name: ast.NewIdent(d.Name),
		Type: &ast.InterfaceType{Methods: &ast.FieldList{List: methods}},
	}}}
	bind := "unigoBind" + d.Name
	var fields []*ast.Field
	var funcs []ast.Decl
	for _, m := range d.Methods {
		ft := g.funcType(m.Params, m.Result)
		fields = append(fields, &ast.Field{
			Names: []*ast.Ident{ast.NewIdent("fn_" + m.Name)},
			Type:  ft,
		})
		funcs = append(funcs, g.bindMethod(bind, m))
	}
	bindDecl := &ast.GenDecl{Tok: gotok.TYPE, Specs: []ast.Spec{&ast.TypeSpec{
		Name: ast.NewIdent(bind),
		Type: &ast.StructType{Fields: &ast.FieldList{List: fields}},
	}}}
	out := []ast.Decl{iface, bindDecl}
	out = append(out, funcs...)
	return out
}

func (g *gen) bindMethod(bind string, m *gast.FuncSig) *ast.FuncDecl {
	params := g.fieldList(m.Params)
	var args []ast.Expr
	for _, p := range m.Params {
		args = append(args, ast.NewIdent(p.Name))
	}
	call := &ast.CallExpr{
		Fun: &ast.SelectorExpr{
			X:   ast.NewIdent("recv"),
			Sel: ast.NewIdent("fn_" + m.Name),
		},
		Args: args,
	}
	var body []ast.Stmt
	if m.Result != nil {
		body = []ast.Stmt{&ast.ReturnStmt{Results: []ast.Expr{call}}}
	} else {
		body = []ast.Stmt{&ast.ExprStmt{X: call}}
	}
	return &ast.FuncDecl{
		Recv: &ast.FieldList{List: []*ast.Field{{
			Names: []*ast.Ident{ast.NewIdent("recv")},
			Type:  ast.NewIdent(bind),
		}}},
		Name: ast.NewIdent(m.Name),
		Type: &ast.FuncType{Params: params, Results: g.resultList(m.Result)},
		Body: &ast.BlockStmt{List: body},
	}
}

func (g *gen) funcDecl(d *gast.FuncDecl) *ast.FuncDecl {
	return &ast.FuncDecl{
		Name: ast.NewIdent(d.Name),
		Type: &ast.FuncType{Params: g.fieldList(d.Params), Results: g.resultList(d.Result)},
		Body: g.block(d.Body),
	}
}

func (g *gen) funcType(params []*gast.VarSpec, result gast.TypeExpr) *ast.FuncType {
	return &ast.FuncType{Params: g.fieldList(params), Results: g.resultList(result)}
}

func (g *gen) fieldList(params []*gast.VarSpec) *ast.FieldList {
	list := &ast.FieldList{}
	for _, p := range params {
		list.List = append(list.List, &ast.Field{
			Names: []*ast.Ident{ast.NewIdent(p.Name)},
			Type:  g.typeExpr(p.Type),
		})
	}
	return list
}

func (g *gen) resultList(t gast.TypeExpr) *ast.FieldList {
	if t == nil {
		return nil
	}
	return &ast.FieldList{List: []*ast.Field{{Type: g.typeExpr(t)}}}
}

func (g *gen) typeExpr(t gast.TypeExpr) ast.Expr {
	switch t := t.(type) {
	case *gast.IdentType:
		return ast.NewIdent(t.Name)
	case *gast.SelectorType:
		return &ast.SelectorExpr{X: ast.NewIdent(t.Pkg), Sel: ast.NewIdent(t.Name)}
	case *gast.PointerType:
		return &ast.StarExpr{X: g.typeExpr(t.Base)}
	case *gast.SliceType:
		return &ast.ArrayType{Elt: g.typeExpr(t.Elem)}
	case *gast.MapType:
		return &ast.MapType{Key: g.typeExpr(t.Key), Value: g.typeExpr(t.Value)}
	default:
		return ast.NewIdent("any")
	}
}

func (g *gen) block(b *gast.Block) *ast.BlockStmt {
	body := &ast.BlockStmt{}
	if b == nil {
		return body
	}
	for _, s := range b.List {
		body.List = append(body.List, g.stmts(s)...)
	}
	return body
}

func (g *gen) stmts(s gast.Stmt) []ast.Stmt {
	switch s := s.(type) {
	case *gast.ConstDecl:
		st := g.declStmt(gotok.CONST, s.Name, g.typeExpr(s.Type), g.expr(s.Value))
		out := []ast.Stmt{st}
		if obj := g.info.Consts[s]; obj != nil && obj.Local && !obj.Used {
			out = append(out, g.blank(s.Name))
		}
		return out
	case *gast.VarDecl:
		return g.varDecl(s)
	case *gast.AssignStmt:
		return []ast.Stmt{&ast.AssignStmt{
			Lhs: []ast.Expr{g.expr(s.Target)},
			Tok: gotok.ASSIGN,
			Rhs: []ast.Expr{g.expr(s.Value)},
		}}
	case *gast.IfStmt:
		return []ast.Stmt{g.ifStmt(s)}
	case *gast.WhileStmt:
		return []ast.Stmt{&ast.ForStmt{Cond: g.expr(s.Cond), Body: g.block(s.Body)}}
	case *gast.ForStmt:
		return []ast.Stmt{&ast.ForStmt{Cond: g.expr(s.Cond), Body: g.block(s.Body)}}
	case *gast.SwitchStmt:
		return []ast.Stmt{g.switchStmt(s)}
	case *gast.ReturnStmt:
		if s.Value == nil {
			return []ast.Stmt{&ast.ReturnStmt{}}
		}
		return []ast.Stmt{&ast.ReturnStmt{Results: []ast.Expr{g.expr(s.Value)}}}
	case *gast.ExprStmt:
		return []ast.Stmt{&ast.ExprStmt{X: g.expr(s.X)}}
	case *gast.Block:
		return []ast.Stmt{g.block(s)}
	default:
		return nil
	}
}

func (g *gen) ifStmt(s *gast.IfStmt) *ast.IfStmt {
	var els ast.Stmt
	if s.Else != nil {
		els = g.block(s.Else)
	}
	for i := len(s.Elifs) - 1; i >= 0; i-- {
		e := s.Elifs[i]
		els = &ast.IfStmt{Cond: g.expr(e.Cond), Body: g.block(e.Body), Else: els}
	}
	return &ast.IfStmt{Cond: g.expr(s.Cond), Body: g.block(s.Body), Else: els}
}

func (g *gen) switchStmt(s *gast.SwitchStmt) *ast.SwitchStmt {
	var list []ast.Stmt
	for _, cs := range s.Cases {
		cc := &ast.CaseClause{Body: []ast.Stmt{g.block(cs.Body)}}
		if !cs.IsDefault && cs.Value != nil {
			cc.List = []ast.Expr{g.expr(cs.Value)}
		}
		list = append(list, cc)
	}
	if sw := g.info.Switches[s]; sw != nil && sw.Enum && sw.Exhaustive {
		list = append(list, &ast.CaseClause{Body: []ast.Stmt{&ast.ExprStmt{X: &ast.CallExpr{
			Fun:  ast.NewIdent("panic"),
			Args: []ast.Expr{&ast.BasicLit{Kind: gotok.STRING, Value: strconv.Quote("unigo: invalid enum")}},
		}}}})
	}
	return &ast.SwitchStmt{Tag: g.expr(s.Tag), Body: &ast.BlockStmt{List: list}}
}

func (g *gen) varDecl(d *gast.VarDecl) []ast.Stmt {
	init := g.info.Inits[d]
	if init == nil {
		init = &check.InitInfo{ErrIndex: -1}
	}
	var stmts []ast.Stmt
	split := len(d.Specs) > 1 || init.Omitted
	if !split && len(d.Specs) == 1 {
		sp := d.Specs[0]
		stmts = append(stmts, g.declStmt(gotok.VAR, sp.Name, g.typeExpr(sp.Type), g.exprAs(d.Value, sp.Type)))
		if d.Else != nil {
			name := init.ErrName
			if name == "" {
				name = sp.Name
			}
			stmts = append(stmts, g.errIf(name, d.Else))
		}
	} else if len(d.Specs) > 0 {
		for _, sp := range d.Specs {
			stmts = append(stmts, g.declStmt(gotok.VAR, sp.Name, g.typeExpr(sp.Type), nil))
		}
		lhs := make([]ast.Expr, 0, len(d.Specs)+1)
		for _, sp := range d.Specs {
			lhs = append(lhs, ast.NewIdent(sp.Name))
		}
		if init.Omitted {
			if d.Else != nil {
				tmp := g.freshErr()
				stmts = append(stmts, g.declStmt(gotok.VAR, tmp, ast.NewIdent("error"), nil))
				lhs = append(lhs, ast.NewIdent(tmp))
				stmts = append(stmts, g.assign(lhs, g.expr(d.Value)))
				stmts = append(stmts, g.errIf(tmp, d.Else))
			} else {
				lhs = append(lhs, ast.NewIdent("_"))
				stmts = append(stmts, g.assign(lhs, g.expr(d.Value)))
			}
		} else {
			stmts = append(stmts, g.assign(lhs, g.expr(d.Value)))
			if d.Else != nil && init.ErrName != "" {
				stmts = append(stmts, g.errIf(init.ErrName, d.Else))
			}
		}
	}
	for _, sp := range d.Specs {
		obj := g.info.Specs[sp]
		if obj != nil && obj.Local && !obj.Used && obj.Kind == check.ObjVar {
			stmts = append(stmts, g.blank(sp.Name))
		}
	}
	return stmts
}

func (g *gen) freshErr() string {
	g.errN++
	return fmt.Sprintf("unigoBindErr%d", g.errN)
}

func (g *gen) errIf(name string, els *gast.ElseReturn) ast.Stmt {
	var ret ast.Stmt
	if els.Bare {
		ret = &ast.ReturnStmt{Results: []ast.Expr{ast.NewIdent(name)}}
	} else if els.Value == nil {
		ret = &ast.ReturnStmt{}
	} else {
		ret = &ast.ReturnStmt{Results: []ast.Expr{g.expr(els.Value)}}
	}
	return &ast.IfStmt{
		Cond: &ast.BinaryExpr{X: ast.NewIdent(name), Op: gotok.NEQ, Y: ast.NewIdent("nil")},
		Body: &ast.BlockStmt{List: []ast.Stmt{ret}},
	}
}

func (g *gen) declStmt(tok gotok.Token, name string, typ ast.Expr, val ast.Expr) ast.Stmt {
	spec := &ast.ValueSpec{Names: []*ast.Ident{ast.NewIdent(name)}, Type: typ}
	if val != nil {
		spec.Values = []ast.Expr{val}
	}
	return &ast.DeclStmt{Decl: &ast.GenDecl{Tok: tok, Specs: []ast.Spec{spec}}}
}

func (g *gen) assign(lhs []ast.Expr, rhs ast.Expr) ast.Stmt {
	return &ast.AssignStmt{Lhs: lhs, Tok: gotok.ASSIGN, Rhs: []ast.Expr{rhs}}
}

func (g *gen) blank(name string) ast.Stmt {
	return &ast.AssignStmt{
		Lhs: []ast.Expr{ast.NewIdent("_")},
		Tok: gotok.ASSIGN,
		Rhs: []ast.Expr{ast.NewIdent(name)},
	}
}

func (g *gen) expr(e gast.Expr) ast.Expr { return g.exprAs(e, nil) }

func (g *gen) exprAs(e gast.Expr, hint gast.TypeExpr) ast.Expr {
	if e == nil {
		return ast.NewIdent("nil")
	}
	switch e := e.(type) {
	case *gast.Ident:
		return ast.NewIdent(e.Name)
	case *gast.BasicLit:
		return g.lit(e)
	case *gast.BinaryExpr:
		return &ast.BinaryExpr{X: g.expr(e.X), Op: opToken(e.Op), Y: g.expr(e.Y)}
	case *gast.UnaryExpr:
		return &ast.UnaryExpr{Op: opToken(e.Op), X: g.expr(e.X)}
	case *gast.CallExpr:
		return g.call(e)
	case *gast.SelectorExpr:
		if si := g.info.Sels[e]; si != nil && si.Kind == check.SelEnum {
			return ast.NewIdent(si.GoName)
		}
		sel := e.Sel
		if si := g.info.Sels[e]; si != nil && si.GoName != "" {
			sel = si.GoName
		}
		return &ast.SelectorExpr{X: g.expr(e.X), Sel: ast.NewIdent(sel)}
	case *gast.IndexExpr:
		return &ast.IndexExpr{X: g.expr(e.X), Index: g.expr(e.Index)}
	case *gast.SliceLit:
		return g.sliceLit(e, hint)
	case *gast.MapLit:
		return g.mapLit(e, hint)
	case *gast.StructLit:
		return g.structLit(e)
	case *gast.InterfaceLit:
		return g.ifaceLit(e)
	default:
		return ast.NewIdent("nil")
	}
}

func quoteString(s string) string {
	if strings.ContainsAny(s, "\"\\") && !strings.ContainsRune(s, '`') && !strings.ContainsAny(s, "\n\r") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}

func (g *gen) lit(e *gast.BasicLit) ast.Expr {
	switch e.Kind {
	case token.String:
		return &ast.BasicLit{Kind: gotok.STRING, Value: quoteString(e.Value)}
	case token.Int:
		return &ast.BasicLit{Kind: gotok.INT, Value: e.Value}
	case token.Float:
		return &ast.BasicLit{Kind: gotok.FLOAT, Value: e.Value}
	case token.True:
		return ast.NewIdent("true")
	case token.False:
		return ast.NewIdent("false")
	case token.Nil:
		return ast.NewIdent("nil")
	default:
		return ast.NewIdent("nil")
	}
}

func (g *gen) call(e *gast.CallExpr) ast.Expr {
	args := make([]ast.Expr, len(e.Args))
	ci := g.info.Calls[e]
	for i, a := range e.Args {
		ge := g.expr(a)
		if ci != nil && ci.StringToBytes && i == 0 {
			ge = &ast.CallExpr{
				Fun:  &ast.ArrayType{Elt: ast.NewIdent("byte")},
				Args: []ast.Expr{ge},
			}
		}
		args[i] = ge
	}
	return &ast.CallExpr{Fun: g.expr(e.Fun), Args: args}
}

func (g *gen) sliceLit(e *gast.SliceLit, hint gast.TypeExpr) ast.Expr {
	var typ ast.Expr
	if _, ok := hint.(*gast.SliceType); ok {
		typ = g.typeExpr(hint)
	} else if t := g.info.Types[e]; t != nil {
		typ = g.goType(t)
	}
	elts := make([]ast.Expr, len(e.Elts))
	for i, el := range e.Elts {
		elts[i] = g.expr(el)
	}
	return &ast.CompositeLit{Type: typ, Elts: elts}
}

func (g *gen) mapLit(e *gast.MapLit, hint gast.TypeExpr) ast.Expr {
	var typ ast.Expr
	if _, ok := hint.(*gast.MapType); ok {
		typ = g.typeExpr(hint)
	} else if t := g.info.Types[e]; t != nil {
		typ = g.goType(t)
	}
	elts := make([]ast.Expr, len(e.Entries))
	for i, ent := range e.Entries {
		elts[i] = &ast.KeyValueExpr{Key: g.expr(ent.Key), Value: g.expr(ent.Value)}
	}
	return &ast.CompositeLit{Type: typ, Elts: elts}
}

func (g *gen) structLit(e *gast.StructLit) ast.Expr {
	elts := make([]ast.Expr, len(e.Fields))
	for i, f := range e.Fields {
		elts[i] = &ast.KeyValueExpr{
			Key:   ast.NewIdent(names.Export(f.Name)),
			Value: g.expr(f.Value),
		}
	}
	return &ast.CompositeLit{Type: g.expr(e.Type), Elts: elts}
}

func (g *gen) ifaceLit(e *gast.InterfaceLit) ast.Expr {
	name := "Bind"
	switch t := e.Type.(type) {
	case *gast.Ident:
		name = t.Name
	case *gast.SelectorExpr:
		name = t.Sel
	}
	elts := make([]ast.Expr, len(e.Methods))
	for i, m := range e.Methods {
		elts[i] = &ast.KeyValueExpr{
			Key: ast.NewIdent("fn_" + m.Name),
			Value: &ast.FuncLit{
				Type: g.funcType(m.Params, m.Result),
				Body: g.block(m.Body),
			},
		}
	}
	return &ast.CompositeLit{Type: ast.NewIdent("unigoBind" + name), Elts: elts}
}

func (g *gen) goType(t types.Type) ast.Expr {
	switch t := t.(type) {
	case *types.Alias:
		return g.objType(t.Obj())
	case *types.Named:
		return g.objType(t.Obj())
	case *types.Basic:
		return ast.NewIdent(t.Name())
	case *types.Pointer:
		return &ast.StarExpr{X: g.goType(t.Elem())}
	case *types.Slice:
		return &ast.ArrayType{Elt: g.goType(t.Elem())}
	case *types.Map:
		return &ast.MapType{Key: g.goType(t.Key()), Value: g.goType(t.Elem())}
	default:
		return ast.NewIdent("any")
	}
}

func (g *gen) objType(obj *types.TypeName) ast.Expr {
	if obj == nil {
		return ast.NewIdent("any")
	}
	if obj.Pkg() == nil || obj.Pkg() == g.info.Pkg {
		return ast.NewIdent(obj.Name())
	}
	local := obj.Pkg().Name()
	if im := g.info.ImportByPkg(obj.Pkg()); im != nil {
		local = im.Local
	}
	return &ast.SelectorExpr{X: ast.NewIdent(local), Sel: ast.NewIdent(obj.Name())}
}

func opToken(k token.Kind) gotok.Token {
	switch k {
	case token.Add:
		return gotok.ADD
	case token.Sub:
		return gotok.SUB
	case token.Mul:
		return gotok.MUL
	case token.Quo:
		return gotok.QUO
	case token.Rem:
		return gotok.REM
	case token.Assign:
		return gotok.ASSIGN
	case token.Eql:
		return gotok.EQL
	case token.Neq:
		return gotok.NEQ
	case token.Lss:
		return gotok.LSS
	case token.Gtr:
		return gotok.GTR
	case token.Leq:
		return gotok.LEQ
	case token.Geq:
		return gotok.GEQ
	case token.Land:
		return gotok.LAND
	case token.Lor:
		return gotok.LOR
	case token.Not:
		return gotok.NOT
	case token.And:
		return gotok.AND
	default:
		return gotok.ILLEGAL
	}
}
